services:
  broker:
    build: ./broker
    container_name: iot_broker
    ports:
      - "8000:8000"
      - "9998:9998/tcp"
    command: python3 iot_broker.py

  light_sensor:
    build: ./client_sensors/light_sensor
    container_name: light_sensor
    command: python3 light_virtual_sensor.py
    restart: unless-stopped
    environment:
      BROKER_IP: "172.16.201.16"
      BROKER_PORT: "9998"

  temperature_sensor:
    build: ./client_sensors/temperature_sensor
    container_name: temperature_sensor
    command: python3 temperature_virtual_sensor.py 
    restart: unless-stopped
    environment:
      BROKER_IP: "172.16.201.16"
      BROKER_PORT: "9998"

  gas_sensor:
    build: ./client_sensors/gas_sensor
    container_name: gas_sensor
    command: python3 gas_virtual_sensor.py
    restart: unless-stopped
    environment:
      BROKER_IP: "172.16.201.16"
      BROKER_PORT: "9998"

  humidity_sensor:
    build: ./client_sensors/humidity_sensor
    container_name: humidity_sensor
    command: python3 humidity_virtual_sensor.py
    restart: unless-stopped
    environment:
      BROKER_IP: "172.16.201.16"
      BROKER_PORT: "9998"

  act_irrigation:
    build: ./client_actuators/act_irrigation
    container_name: act_irrigation
    command: python3 act_irrigation.py
    restart: unless-stopped
    environment:
      BROKER_IP: "172.16.201.16"
      BROKER_PORT: "9998"

  act_curtain:
    build: ./client_actuators/act_curtain
    container_name: act_curtain
    command: python3 act_curtain.py
    restart: unless-stopped
    environment:
      BROKER_IP: "172.16.201.16"
      BROKER_PORT: "9998"

  # client:
  #   build: ./client
  #   container_name: iot_dashboard
  #   command: python3 iot_client.py
  #   restart: unless-stopped
  #   environment:
  #     BROKER_IP: "172.16.201.16"
  #     BROKER_PORT: "9998"
  #     DISPLAY: $DISPLAY
  #     XAUTHORITY: /.Xauthority
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #     - ~/.Xauthority:/.Xauthority:ro